permissions:
  contents: write
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: stable # https://github.com/actions/go-versions/blob/main/versions-manifest.json
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
